---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: 如果您的環境符合要求，您可以依照下列步驟安裝Trident Protect。 
---
= 安裝並設定Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果您的環境符合Trident Protect 的要求，您可以依照下列步驟在叢集上安裝Trident Protect。您可以從NetApp取得Trident Protect，或從您自己的私人註冊表中安裝它。如果您的叢集無法存取互聯網，從私有註冊表安裝會很有幫助。


NOTE: 預設情況下， Trident Protect 會收集有助於處理您可能提交的任何NetApp支援案例的支援訊息，包括叢集和受管應用程式的日誌、指標和拓撲資訊。Trident Protect 會按方案每日傳送這些支援包給NetApp 。安裝Trident Protect 時，您可以選擇停用此支援包集合。您可以手動操作link:trident-protect-generate-support-bundle.html["產生支援服務組合"]隨時。



== 安裝Trident Protect

[role="tabbed-block"]
====
.從NetApp安裝Trident Protect
--
.步驟
. 新增Trident Helm儲存庫：
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. 安裝Trident Protect CRD：
+
[source, console]
----
helm install trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2410.1 --create-namespace --namespace trident-protect
----
. 使用 Helm 透過以下指令之一安裝Trident Protect。代替 `<name_of_cluster>`集群名稱將分配給集群，並用於標識集群的備份和快照：
+
** 正常安裝Trident Protect：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2410.1 --create-namespace --namespace trident-protect
----
** 安裝Trident Protect 並停用每日定期上傳的Trident Protect AutoSupport支援套件：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set autoSupport.enabled=false --set clusterName=<name_of_cluster> --version 100.2410.1 --create-namespace --namespace trident-protect
----




--
.從私人註冊表安裝Trident Protect
--
如果您的 Kubernetes 叢集無法存取互聯網，您可以從私人鏡像倉庫安裝Trident Protect。在這些範例中，請將括號中的值替換為您環境中的資訊：

.步驟
. 將下列影像拉到您的本機電腦，更新標記，然後將它們推送到您的私人登錄：
+
[source, console]
----
netapp/controller:24.10.1
netapp/restic:24.10.1
netapp/kopia:24.10.1
netapp/trident-autosupport:24.10.0
netapp/exechook:24.10.1
netapp/resourcebackup:24.10.1
netapp/resourcerestore:24.10.1
netapp/resourcedelete:24.10.1
bitnami/kubectl:1.30.2
kubebuilder/kube-rbac-proxy:v0.16.0
----
+
例如：

+
[source, console]
----
docker pull netapp/controller:24.10.1
----
+
[source, console]
----
docker tag netapp/controller:24.10.1 <private-registry-url>/controller:24.10.1
----
+
[source, console]
----
docker push <private-registry-url>/controller:24.10.1
----
. 建立Trident Protect 系統命名空間：
+
[source, console]
----
kubectl create ns trident-protect
----
. 登入登錄：
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. 建立用於私人登錄驗證的拉出密碼：
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. 新增Trident Helm儲存庫：
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. 建立一個名為的文件 `protectValues.yaml`。請確保其中包含以下Trident Protect 設定：
+
[source, yaml]
----
---
image:
  registry: <private-registry-url>
imagePullSecrets:
  - name: regcred
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
    - name: regcred
webhooksCleanup:
  imagePullSecrets:
    - name: regcred
----
. 安裝Trident Protect CRD：
+
[source, console]
----
helm install trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2410.1 --create-namespace --namespace trident-protect
----
. 使用 Helm 透過以下指令之一安裝Trident Protect。代替 `<name_of_cluster>`集群名稱將分配給集群，並用於標識集群的備份和快照：
+
** 正常安裝Trident Protect：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2410.1 --create-namespace --namespace trident-protect -f protectValues.yaml
----
** 安裝Trident Protect 並停用每日定期上傳的Trident Protect AutoSupport支援套件：
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set autoSupport.enabled=false --set clusterName=<name_of_cluster> --version 100.2410.1 --create-namespace --namespace trident-protect -f protectValues.yaml
----




--
====


== 指定Trident Protect 容器資源限制

安裝Trident Protect 後，您可以使用設定檔來指定Trident Protect 容器的資源限制。設定資源限制可以控制Trident Protect 作業消耗叢集資源的程度。

.步驟
. 建立名為的檔案 `resourceLimits.yaml`。
. 根據您的環境需求，在檔案中填入Trident Protect 容器的資源限制選項。
+
以下範例組態檔顯示可用的設定，並包含每個資源限制的預設值：

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. 套用檔案中的值 `resourceLimits.yaml`：
+
[source, console]
----
helm upgrade trident-protect -n trident-protect -f <resourceLimits.yaml> --reuse-values
----

